// Contain all the variables used to test removeFalsy
// path : test/var.ts
// --

const object = {
    a: null,
    b: -1,
    c: " ",
    d: "",
    e: undefined,
    f: "    string    ",
    g: 0,
    h: {
      x       : "string",
      xx      : undefined,
      xxx     : null,
      xxxx    : 0,
      xxxxx   : " ",
      xxxxxx  : "",
      xxxxxxx : "    string    ",
      xxxxxxxx: 1,
    },
    i: [
      null,
      " ",
      "",
      0,
      undefined,
      1,
      "string",
      "    string    ",
      {
        x       : "string",
        xx      : undefined,
        xxx     : null,
        xxxx    : 0,
        xxxxx   : " ",
        xxxxxx  : "",
        xxxxxxx : "    string    ",
        xxxxxxxx: 1,
      },
      [null, " ", "", 0, undefined, 1, "string", "    string    ", -1],
    ],
  },
  array = [
    null,
    " ",
    "",
    0,
    undefined,
    1,
    false,
    true,
    [true, false, true, false, false],
    "string",
    "    string    ",
    object,
    [null, " ", "", 0, undefined, 1, "string", "    string    ", -1],
  ],
  und              = undefined,
  nullVar          = null,
  string           = "string",
  spacedString     = "   ",
  nullString       = "",
  nonTrimmedString = "    string    ",
  int              = 12,
  nullInt          = 0,
  bool             = true,
  nullBool         = false,
  boolArray        = [true, false];
//---------------------------------------------//
export { object, array, string, spacedString, nullString, nonTrimmedString, int, nullInt, bool, nullBool, boolArray, und, nullVar };

